name: Deploy Docker

run-name: ${{ github.actor }} is testing out Gitea Actions 🚀

on: [push]
jobs:
  Deploy-Docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Docker
        run: curl -fsSL https://get.docker.com | sh

      - name: Login to gitea container registry
        uses: docker/login-action@v2
        with:
          registry: http://127.0.0.1:4000
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./src
          push: true
          tags: 127.0.0.1:4000/${{ github.repository }}
